export default{
    name:"Bullet",
    components:[
        {
            type:"TriangleComponent",
            values:[
                {
                    key:"fill",
                    value:"White"
                },
                {
                    key:"stroke",
                    value:"Black"
                },
                {
                    key:"base",
                    value:15
                },
                {
                    key:"height",
                    value:15
                },
            ]
        },
        {
            type:"BulletBehavior"
        },
        {
            type:"PointCollider"
        }
    ]
}